export  const TransactionStatusTypes = {
	INGRESADO: "INGRESADO",
	PENDIENTE_DE_ACREDITACION: "PENDIENTE_DE_ACREDITACION",
	CUIT_INCORRECTO: "CUIT_INCORRECTO",
	PAYMENT: "PAYMENT",
	PROVIDER_CASH_DELIVERY: "PROVIDER_CASH_DELIVERY",
	CONFIRMADO: "CONFIRMADO",
	RECHAZADO: "RECHAZADO",
	ERROR_DE_CARGA: "ERROR_DE_CARGA",
};